[pytest]
testpaths = .
python_files = test_*.py
markers =
    regression: mark a test as a regression test
    smoke: mark a test as a smoke test
    integration: mark a test as an integration test
    unit: mark a test as a unit test
    login: mark a test as a login test
